// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Services.AuthService.Infrastructure;

#nullable disable

namespace Services.AuthService.Infrastructure.Persistence.Migrations.postgre
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bytecode_auth")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.AuthService.Domain.Entities.AccountActivationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время создания записи");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время истечения срока");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("VerificationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время подтверждения");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Токен верификации");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_AccountActivationRecords_ExpiresAt");

                    b.HasIndex("VerificationToken")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_AccountActivationRecords_UserId_ExpiresAt");

                    b.ToTable("AccountActivationRecords", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Действие");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время записи");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Подробности");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasComment("IP адрес");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasComment("User-Agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_UserId_CreatedAt");

                    b.ToTable("AuditLogs", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.FailedLoginAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время попытки входа");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("IX_FailedLoginAttempts_AttemptedAt");

                    b.HasIndex("UserId", "AttemptedAt")
                        .HasDatabaseName("IX_FailedLoginAttempts_UserId_AttemptedAt");

                    b.ToTable("FailedLoginAttempts", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.PasswordResetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время создания токена");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время истечения токена");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Использован ли токен");

                    b.Property<string>("ResetToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Токен сброса пароля");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_PasswordResets_ExpiresAt");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("IX_PasswordResets_UserId_IsUsed");

                    b.ToTable("PasswordResets", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Instant>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата создания");

                    b.Property<Instant>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата истечения");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRevoked");

                    b.HasIndex("UserId", "UserAgent");

                    b.ToTable("RefreshTokens", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Идентификатор аватара");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата регистрации");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата удаления");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Почта");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("boolean")
                        .HasComment("Является ли автором");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Имя");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Ник");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Хеш пароля");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Фамилия");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата изменения");

                    b.Property<bool>("VerifyMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Подтверждение аккаунта");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("UsersAuthService", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.UserRolesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("Идентификатор роли");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.UserSettingEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("JsonSettings")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings", "bytecode_auth");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.AccountActivationEntity", b =>
                {
                    b.HasOne("Services.AuthService.Domain.Entities.UserEntity", "User")
                        .WithMany("UserVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.UserRolesEntity", b =>
                {
                    b.HasOne("Services.AuthService.Domain.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Services.AuthService.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
