syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option csharp_namespace = "UserService.Proto";

// Сервис для управления пользователями
service UserGrpcService {
  // Добавление пользователя
  rpc CreateUser(CreateUserRequest) returns (UserBooleanResponse);
  // Выдача авторских прав
  rpc CreateAuthorUser(CreateAuthorRequest) returns (UserAuthorInfoResponse);
}

message CreateUserRequest{
  // Идентификатор из AuthService
  string user_id = 1;
}

message CreateAuthorRequest{
  // Идентификатор пользователя
  string user_id = 1;
}

message GetUserRequest{
  // Идентификатор пользователя
  string user_id = 1;
}

message UserInfoResponse{
  string user_id = 1;
  string surname = 2;
  string name = 3;
  string nickname = 4;
  string email = 5;
  bool isAuthor = 6;
  google.protobuf.Timestamp createdAt = 7;
  optional google.protobuf.Timestamp updatedAt = 8;
  optional google.protobuf.Timestamp deletedAt = 9;
}

message UserBooleanResponse{
  bool success = 1;
}

message UserAuthorInfoResponse{
  string author_id = 1;
  UserInfoResponse user = 2;
}