// <auto-generated />
using System;
using BusinessCardProject.Server.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessCardProject.Server.Core.Infrastructure.Persistence.Migrations.postgre
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260119182942_Migration_0.0.1")]
    partial class Migration_001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.VideoCourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("DisplayOrder")
                        .HasComment("Порядок сортировки");

                    b.Property<bool>("IsShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsShow")
                        .HasComment("Признак, будет ли показываться курс на странице");

                    b.Property<Guid>("_courseAuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CourseAuthorId")
                        .HasComment("ID автора");

                    b.Property<DateTime>("_courseDatePublished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CourseDatePublished")
                        .HasComment("Дата публикации");

                    b.Property<string>("_courseDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CourseDescription")
                        .HasComment("Описание");

                    b.Property<int>("_courseDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("CourseDiscount")
                        .HasComment("Размер скидки");

                    b.Property<string>("_courseImg")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CourseImg")
                        .HasComment("Изображение");

                    b.Property<string>("_courseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CourseName")
                        .HasComment("Название");

                    b.Property<double>("_coursePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("CoursePrice");

                    b.Property<double>("_courseRate")
                        .HasColumnType("double precision")
                        .HasColumnName("CourseRate")
                        .HasComment("Рейтинг");

                    b.Property<bool>("_isFree")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFree")
                        .HasComment("Признак, платный курс или нет");

                    b.Property<string>("_linkCourseOnRutube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkCourseOnRutube")
                        .HasComment("Ссылка на рутуб");

                    b.Property<string>("_linkCourseOnVkVideo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkCourseOnVkVideo")
                        .HasComment("Ссылка на ВК видео");

                    b.Property<string>("_linkCourseOnYoutube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkCourseOnYoutube")
                        .HasComment("Ссылка на ютуб");

                    b.HasKey("Id");

                    b.ToTable("VideoCourse", "dev_prod");
                });
#pragma warning restore 612, 618
        }
    }
}
