// <auto-generated />
using System;
using BusinessCardProject.Server.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessCardProject.Server.Core.Infrastructure.Persistence.Migrations.postgre
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260127175033_Migration_0.0.2")]
    partial class Migration_002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dev_prod")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseAuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("_authorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("_authorNickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nickname");

                    b.Property<string>("_authorPatronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Patronymic");

                    b.Property<string>("_authorSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Surname");

                    b.HasKey("Id");

                    b.HasIndex("_authorNickName")
                        .IsUnique();

                    b.ToTable("CourseAuthors", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("_courseThemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Description")
                        .HasComment("Описание");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name")
                        .HasComment("Название");

                    b.HasKey("Id");

                    b.HasIndex("_courseThemeId");

                    b.ToTable("Modules", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseThemeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("_programmingLanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("_themeDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Description")
                        .HasComment("Описание");

                    b.Property<string>("_themeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name")
                        .HasComment("Название");

                    b.Property<Guid>("_typeOfCourseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("_programmingLanguageId");

                    b.HasIndex("_typeOfCourseId");

                    b.ToTable("Themes", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.ProgrammingLanguageCourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("_countSelectedUser")
                        .HasColumnType("integer")
                        .HasColumnName("CountSelectedUser")
                        .HasComment("Количество людей использующий ЯП");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name")
                        .HasComment("Название языка программирования");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.VideoCourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("DisplayOrder")
                        .HasComment("Порядок сортировки");

                    b.Property<bool>("IsShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsShow")
                        .HasComment("Признак, будет ли показываться курс на странице");

                    b.Property<Guid>("_courseAuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CourseAuthorId")
                        .HasComment("ID автора");

                    b.Property<DateTime>("_courseDatePublished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CourseDatePublished")
                        .HasComment("Дата публикации");

                    b.Property<string>("_courseDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CourseDescription")
                        .HasComment("Описание");

                    b.Property<int>("_courseDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("CourseDiscount")
                        .HasComment("Размер скидки");

                    b.Property<string>("_courseImg")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CourseImg")
                        .HasComment("Изображение");

                    b.Property<Guid>("_courseModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("_courseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CourseName")
                        .HasComment("Название");

                    b.Property<double>("_coursePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("CoursePrice")
                        .HasComment("Стоимость");

                    b.Property<double>("_courseRate")
                        .HasColumnType("double precision")
                        .HasColumnName("CourseRate")
                        .HasComment("Рейтинг");

                    b.Property<bool>("_isFree")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFree")
                        .HasComment("Признак, платный курс или нет");

                    b.Property<string>("_linkCourseOnRutube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkCourseOnRutube")
                        .HasComment("Ссылка на рутуб");

                    b.Property<string>("_linkCourseOnVkVideo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkCourseOnVkVideo")
                        .HasComment("Ссылка на ВК видео");

                    b.Property<string>("_linkCourseOnYoutube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkCourseOnYoutube")
                        .HasComment("Ссылка на ютуб");

                    b.HasKey("Id");

                    b.HasIndex("_courseAuthorId");

                    b.HasIndex("_courseModuleId");

                    b.ToTable("VideoCourse", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Enums.Course.TypeOfCourseEnum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TypeOfCourses", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseThemeEntity", "CourseTheme")
                        .WithMany("CourseModules")
                        .HasForeignKey("_courseThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseTheme");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseThemeEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.ProgrammingLanguageCourseEntity", "ProgrammingLanguages")
                        .WithMany("CourseThemes")
                        .HasForeignKey("_programmingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessCardProject.Server.Core.Domain.Enums.Course.TypeOfCourseEnum", "TypeOfCourse")
                        .WithMany()
                        .HasForeignKey("_typeOfCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguages");

                    b.Navigation("TypeOfCourse");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.VideoCourseEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseAuthorEntity", "CourseAuthor")
                        .WithMany("VideoCourses")
                        .HasForeignKey("_courseAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", "CourseModule")
                        .WithMany("VideoCourses")
                        .HasForeignKey("_courseModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAuthor");

                    b.Navigation("CourseModule");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseAuthorEntity", b =>
                {
                    b.Navigation("VideoCourses");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", b =>
                {
                    b.Navigation("VideoCourses");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseThemeEntity", b =>
                {
                    b.Navigation("CourseModules");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.ProgrammingLanguageCourseEntity", b =>
                {
                    b.Navigation("CourseThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
