// <auto-generated />
using System;
using BusinessCardProject.Server.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessCardProject.Server.Core.Infrastructure.Persistence.Migrations.postgre
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dev_prod")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseAuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("_authorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("_authorNickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nickname");

                    b.Property<string>("_authorPatronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Patronymic");

                    b.Property<string>("_authorSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Surname");

                    b.HasKey("Id");

                    b.HasIndex("_authorNickName")
                        .IsUnique();

                    b.ToTable("CourseAuthors", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseThemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Description")
                        .HasComment("Описание");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name")
                        .HasComment("Название");

                    b.HasKey("Id");

                    b.HasIndex("CourseThemeId");

                    b.ToTable("Modules", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseTheme.CourseThemeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uuid");

                    b.Property<int>("_displayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("DisplayOrder")
                        .HasComment("Порядок отображения");

                    b.Property<bool>("_isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive")
                        .HasComment("Нужно ли отображать");

                    b.Property<bool>("_isFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsFree")
                        .HasComment("Платная ли тема");

                    b.Property<string>("_themeDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Description")
                        .HasComment("Описание");

                    b.Property<string>("_themeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name")
                        .HasComment("Название");

                    b.Property<Guid>("_typeOfCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("TypeOfCourse");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("Themes", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseTheme.ThemeRecommendationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseThemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Title")
                        .HasComment("Рекомендация");

                    b.HasKey("Id");

                    b.HasIndex("CourseThemeId");

                    b.ToTable("ThemeRecommendations", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.ProgrammingLanguageCourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("_countSelectedUser")
                        .HasColumnType("integer")
                        .HasColumnName("CountSelectedUser")
                        .HasComment("Количество людей использующий ЯП");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name")
                        .HasComment("Название языка программирования");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.VideoCourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseAuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("DisplayOrder")
                        .HasComment("Порядок сортировки");

                    b.Property<bool>("IsShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsShow")
                        .HasComment("Признак, будет ли показываться курс на странице");

                    b.Property<Instant>("_courseDatePublished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DatePublished")
                        .HasComment("Дата публикации");

                    b.Property<string>("_courseDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description")
                        .HasComment("Описание");

                    b.Property<int>("_courseDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("Discount")
                        .HasComment("Размер скидки");

                    b.Property<string>("_courseImg")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Img")
                        .HasComment("Изображение");

                    b.Property<string>("_courseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name")
                        .HasComment("Название");

                    b.Property<double>("_coursePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("Price")
                        .HasComment("Стоимость");

                    b.Property<double>("_courseRate")
                        .HasColumnType("double precision")
                        .HasColumnName("Rate")
                        .HasComment("Рейтинг");

                    b.Property<bool>("_isFree")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFree")
                        .HasComment("Признак, платный курс или нет");

                    b.Property<string>("_linkCourseOnRutube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkOnRutube")
                        .HasComment("Ссылка на рутуб");

                    b.Property<string>("_linkCourseOnVkVideo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkOnVkVideo")
                        .HasComment("Ссылка на ВК видео");

                    b.Property<string>("_linkCourseOnYoutube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkOnYoutube")
                        .HasComment("Ссылка на ютуб");

                    b.HasKey("Id");

                    b.HasIndex("CourseAuthorId");

                    b.HasIndex("CourseModuleId");

                    b.ToTable("VideoCourse", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.User.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NickName")
                        .HasComment("Почта");

                    b.Property<Instant?>("DateOfDeletion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateOfDeletion")
                        .HasComment("Дата деактивации аккаунта");

                    b.Property<Instant>("DateOfRegistered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateOfRegistered")
                        .HasComment("Дата регистрации");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email")
                        .HasComment("Почта");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name")
                        .HasComment("Имя");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Patronymic")
                        .HasComment("Отчество");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("Настройки пользователя");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Surname")
                        .HasComment("Фамилия");

                    b.Property<bool>("_isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isActive")
                        .HasComment("Признак работоспособности профиля");

                    b.Property<bool>("_isBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isBlocked")
                        .HasComment("Признак блокировки");

                    b.Property<string>("_password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Password")
                        .HasComment("Пароль");

                    b.HasKey("Id");

                    b.HasIndex("AltName")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserProfiles", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.User.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserRole")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId")
                        .HasComment("Ид роли пользователя");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("User_Roles", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Enums.Course.TypeOfCourseEnum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Название типа курса");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TypeOfCourses", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Enums.User.UserRoleEnum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Название роли");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TypeUserRoles", "dev_prod");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseTheme.CourseThemeEntity", "CourseTheme")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CourseTheme");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseTheme.CourseThemeEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.ProgrammingLanguageCourseEntity", "ProgrammingLanguages")
                        .WithMany("CourseThemes")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguages");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseTheme.ThemeRecommendationEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseTheme.CourseThemeEntity", "CourseTheme")
                        .WithMany("ThemeRecommendations")
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CourseTheme");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.VideoCourseEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseAuthorEntity", "CourseAuthor")
                        .WithMany("VideoCourses")
                        .HasForeignKey("CourseAuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", "CourseModule")
                        .WithMany("VideoCourses")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CourseAuthor");

                    b.Navigation("CourseModule");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.User.UserRoleEntity", b =>
                {
                    b.HasOne("BusinessCardProject.Server.Core.Domain.Aggregates.User.UserProfileEntity", "UserProfile")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseAuthorEntity", b =>
                {
                    b.Navigation("VideoCourses");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseModuleEntity", b =>
                {
                    b.Navigation("VideoCourses");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.CourseTheme.CourseThemeEntity", b =>
                {
                    b.Navigation("CourseModules");

                    b.Navigation("ThemeRecommendations");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.Course.ProgrammingLanguageCourseEntity", b =>
                {
                    b.Navigation("CourseThemes");
                });

            modelBuilder.Entity("BusinessCardProject.Server.Core.Domain.Aggregates.User.UserProfileEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
