<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeBeam.MudBlazor.Extensions.Qr" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.20" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="8.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\BasePages\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ApiEndpoints\ApiEndpoints.csproj" />
    <ProjectReference Include="..\..\ContractualDTOs\ContractualDtos\ContractualDtos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\images\Donation\QR_Dark.png" />
    <_ContentIncludedByDefault Remove="wwwroot\images\Donation\QR_Light.png" />
    <_ContentIncludedByDefault Remove="Pages\RatingPage\Rating.razor" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Pages\BasePages\AboutUsPage\AboutUs.razor" />
    <AdditionalFiles Include="Pages\BasePages\CoursesPages\BlockMyCoursesPage\BlockMyCoursesPage.razor" />
    <AdditionalFiles Include="Pages\BasePages\CoursesPages\CourseThemesPage\CourseIllustration\CoreIllustrationPage.razor" />
    <AdditionalFiles Include="Pages\BasePages\CoursesPages\CourseThemesPage\ThemesCoursePage.razor" />
    <AdditionalFiles Include="Pages\BasePages\DonationPage\Donation.razor" />
    <AdditionalFiles Include="Pages\BasePages\HomePage\Home.razor" />
    <AdditionalFiles Include="Pages\BasePages\PoliciesPages\PrivacyPolicy.razor" />
    <AdditionalFiles Include="Pages\BasePages\PoliciesPages\UserAgreement.razor" />
    <AdditionalFiles Include="Pages\BasePages\RatingPage\Rating.razor" />
  </ItemGroup>

</Project>
