<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <RootNamespace>BusinessCardProject.Client</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="8.0.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.70.0" />
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.70.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CodeBeam.MudBlazor.Extensions.Qr" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.20" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="8.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\BasePages\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\images\Donation\QR_Dark.png" />
    <_ContentIncludedByDefault Remove="wwwroot\images\Donation\QR_Light.png" />
    <_ContentIncludedByDefault Remove="Pages\RatingPage\Rating.razor" />
    <_ContentIncludedByDefault Remove="Pages\AdminPanelPages\Сomponents\CourseThemes\Components\UniversalPropertyDialog.razor" />
    <_ContentIncludedByDefault Remove="publish\web.config" />
    <_ContentIncludedByDefault Remove="publish\ByteCodePlatform.Client.staticwebassets.endpoints.json" />
    <_ContentIncludedByDefault Remove="publish\emcc-props.json" />
    <_ContentIncludedByDefault Remove="publish\wwwroot\_framework\blazor.boot.json" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Pages\BasePages\AboutUsPage\AboutUs.razor" />
    <AdditionalFiles Include="Pages\BasePages\CoursesPages\BlockMyCoursesPage\BlockMyCoursesPage.razor" />
    <AdditionalFiles Include="Pages\BasePages\CoursesPages\CourseThemesPage\CourseIllustration\CoreIllustrationPage.razor" />
    <AdditionalFiles Include="Pages\BasePages\CoursesPages\CourseThemesPage\ThemesCoursePage.razor" />
    <AdditionalFiles Include="Pages\BasePages\DonationPage\Donation.razor" />
    <AdditionalFiles Include="Pages\BasePages\HomePage\Home.razor" />
    <AdditionalFiles Include="Pages\BasePages\PoliciesPages\PrivacyPolicy.razor" />
    <AdditionalFiles Include="Pages\BasePages\PoliciesPages\UserAgreement.razor" />
    <AdditionalFiles Include="Pages\BasePages\RatingPage\Rating.razor" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\auth-service.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\course-service.proto"  GrpcServices="Client" />
    <Protobuf Include="Protos\user-service.proto"  GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

</Project>
