<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <RootNamespace>BusinessCardProject.Client</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="8.0.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.70.0" />
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.70.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CodeBeam.MudBlazor.Extensions.Qr" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.20" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="8.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Update="Dockerfile">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
    <Content Update="nginx.conf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <Protobuf Include="Entities\Protos\auth-service.proto">
      <Generator>MSBuild:Compile</Generator>
    </Protobuf>
    <Protobuf Include="Entities\Protos\course-service.proto">
      <Generator>MSBuild:Compile</Generator>
    </Protobuf>
    <Protobuf Include="Entities\Protos\user-service.proto">
      <Generator>MSBuild:Compile</Generator>
    </Protobuf>
  </ItemGroup>
  
  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\BasePages\CoursesPages\CourseThemesPage\CourseIllustration\CoreIllustrationPage.razor" />
  </ItemGroup>

</Project>
