server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;
    
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /AuthGrpcService {
        grpc_pass grpcs://bytecode-auth:5012;

        grpc_ssl_verify off;

        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto $scheme;

        grpc_read_timeout 300s;
        grpc_send_timeout 300s;
    }

    location /CourseGrpcService {
        grpc_pass grpcs://bytecode-core:5221;
        
        grpc_ssl_verify off;
        
        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto $scheme;

        grpc_read_timeout 300s;
        grpc_send_timeout 300s;
    }
    
    location /FilesServiceGrpcService {
        proxy_pass https://bytecode-fileservice:5036;
        proxy_http_version 1.1;

        proxy_hide_header Cache-Control;
        proxy_hide_header Pragma;
        proxy_hide_header Expires;

        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }
    
    location ~* \.(wasm|js|css|png|jpg|svg|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}