<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="9.0.0"/>
        <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.0"/>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\ByteCodePlatform.Application\ByteCodePlatform.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.cryptography.keyderivation\9.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Cryptography.KeyDerivation.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
