// <auto-generated />
using System;
using ByteCodePlatform.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ByteCodePlatform.Infrastructure.Persistence.Migrations.postgre
{
    [DbContext(typeof(ByteCodeCoreDbContext))]
    [Migration("20260512165824_Migration_ByteCode_Core_0.0.2")]
    partial class Migration_ByteCode_Core_002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bytecode_core")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата регистрации");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата удаления");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата изменения");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Authors", "bytecode_core");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseContentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseModuleId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата добавления");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ссылка на обложку видео");

                    b.Property<string>("LinkOnRutube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ссылка рутуб");

                    b.Property<string>("LinkOnVk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ссылка вк видео");

                    b.Property<string>("LinkOnYouTube")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ссылка ютуб");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Название видео");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата изменения");

                    b.HasKey("Id");

                    b.HasIndex("CourseModuleId");

                    b.ToTable("CourseContents", "bytecode_core");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseThemeId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата добавления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Название модуля");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата удаления");

                    b.HasKey("Id");

                    b.HasIndex("CourseThemeId");

                    b.ToTable("CourseModules", "bytecode_core");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseThemeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ссылка на обложку");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата добавления");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Описание");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Название");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("numeric")
                        .HasComment("Старая цена");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasComment("Текущая цена");

                    b.Property<Guid>("ProgrammingLanguageCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата изменения");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProgrammingLanguageCategoryId");

                    b.ToTable("CourseThemes", "bytecode_core");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.ProgrammingLanguageCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Название модуля");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguageCategories", "bytecode_core");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата регистрации");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата удаления");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Почта");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("boolean")
                        .HasComment("Является ли автором");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Имя");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Ник");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Фамилия");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата изменения");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("Users", "bytecode_core");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.AuthorEntity", b =>
                {
                    b.HasOne("ByteCodePlatform.Domain.Entities.UserEntity", "User")
                        .WithOne("Author")
                        .HasForeignKey("ByteCodePlatform.Domain.Entities.AuthorEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseContentEntity", b =>
                {
                    b.HasOne("ByteCodePlatform.Domain.Entities.Course.CourseModuleEntity", "CourseModule")
                        .WithMany("Contents")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseModule");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseModuleEntity", b =>
                {
                    b.HasOne("ByteCodePlatform.Domain.Entities.Course.CourseThemeEntity", "CourseTheme")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseTheme");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseThemeEntity", b =>
                {
                    b.HasOne("ByteCodePlatform.Domain.Entities.AuthorEntity", "Author")
                        .WithMany("Courses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ByteCodePlatform.Domain.Entities.Course.ProgrammingLanguageCategoryEntity", "ProgrammingLanguageCategory")
                        .WithMany("CoursesThemes")
                        .HasForeignKey("ProgrammingLanguageCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ProgrammingLanguageCategory");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.AuthorEntity", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseModuleEntity", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.CourseThemeEntity", b =>
                {
                    b.Navigation("CourseModules");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.Course.ProgrammingLanguageCategoryEntity", b =>
                {
                    b.Navigation("CoursesThemes");
                });

            modelBuilder.Entity("ByteCodePlatform.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Author")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
