<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Common\Enums\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
        <PackageReference Include="MediatR" Version="11.0.0" />
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
        <PackageReference Include="NodaTime" Version="3.3.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ByteCodePlatform.Domain\ByteCodePlatform.Domain.csproj" />
      <ProjectReference Include="..\ContractualDTOs\Dtos\Dtos.csproj" />
      <ProjectReference Include="..\ContractualDTOs\Requests\Requests.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Google.Protobuf">
        <HintPath>..\..\..\..\.nuget\packages\google.protobuf\3.23.1\lib\net5.0\Google.Protobuf.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
